from __future__ import annotations

import json
import re
from dataclasses import replace
from pathlib import Path

from ebam_gcode_studio.core import (
    APP_VERSION,
    ProcessSettings,
    audit_gcode,
    build_experience_calibration_profile,
    experience_profile_to_json,
    generate_rotational_shell,
    layer_parameters,
    estimate_bead_width_mm,
    _recompute_layer_after_experience,
)

CYLINDER = {
    "profile_type": "straight_cup",
    "height_mm": 8.0,
    "bottom_diameter_mm": 79.0,
    "top_diameter_mm": 79.0,
    "max_diameter_mm": 79.0,
    "wall_thickness_mm": 1.0,
    "bottom_solid_mm": 0.0,
    "resolution": 96,
}
TAPERED = {
    **CYLINDER,
    "profile_type": "cone",
    "bottom_diameter_mm": 79.0,
    "top_diameter_mm": 85.0,
    "max_diameter_mm": 85.0,
}

BASE = ProcessSettings(
    layer_height=0.5,
    hatch_spacing=1.0,
    rotational_path_strategy="rotary_c_rings",
    rotational_radial_step_mm=1.0,
    rotary_c_motion_mode="no_pause_flat_rings",
    rotary_c_transition_angle_deg=17.0,
    rotary_c_direction="C+",
    rotary_c_max_deg_min=10000.0,
    rotary_c_auto_limit_feed=True,
    rotary_c_radius_variation_tolerance_mm=0.05,
    feed_bottom_mm_min=450.0,
    feed_top_mm_min=450.0,
    voltage_kv=60.0,
    beam_current_mode="current",
    beam_current_bottom_ma=22.0,
    beam_current_top_ma=22.0,
    current_min_ma=0.0,
    current_max_ma=50.0,
    wire_diameter_mm=1.2,
    deposition_efficiency=0.8,
    wire_feed_mode="auto",
    rotary_c_disable_layer_pauses=True,
    rotary_c_disable_w_retract=True,
    rotary_c_disable_z_hop=True,
    include_comments=False,
)


def must(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def profile_json() -> str:
    profile = build_experience_calibration_profile(
        program_height_mm=8.0,
        base_z_step_mm=0.5,
        radius_mm=39.5,
        cfeed_code_deg_min=450.0,
        e2_code_mm_s=4.0,
        e0_code_ma=22.0,
        voltage_kv=60.0,
        wire_diameter_mm=1.2,
        deposition_efficiency=0.8,
        actual_height_mm=7.0,
        outer_diameter_mm=83.0,
        inner_diameter_mm=75.0,
        target_wall_mm=3.0,
        problem_start_height_mm=4.0,
        max_z_offset_mm=-0.5,
        feed_override_stable_pct=100.0,
        wire_override_stable_pct=100.0,
        current_override_stable_pct=100.0,
        feed_override_upper_pct=110.0,
        wire_override_upper_pct=90.0,
        current_override_upper_pct=105.0,
        test_height_mm=8.0,
    )
    must(abs(profile["source"]["deposition_efficiency"] - 0.8) < 1e-9, "eta not saved in profile")
    return experience_profile_to_json(profile)


def main() -> None:
    checks: list[str] = []

    # 1. Default controller compatibility remains M68; overrides are untouched.
    default_res = generate_rotational_shell(CYLINDER, BASE)
    must(f"Generated by EBAM G-code Studio {APP_VERSION}" in default_res.gcode, "version header missing")
    must("G64 P0.080 Q0.000" in default_res.gcode, "G64 P/Q header missing")
    must("M49" not in default_res.gcode and "M50" not in default_res.gcode, "program must not disable external overrides")
    must(default_res.stats["analog_output_code_effective"] == "M68", "default analog mode changed away from M68")
    checks.append("default_m68_and_overrides_untouched")

    # 2. M67 request without HAL confirmation must safely fall back to M68.
    fallback = generate_rotational_shell(
        CYLINDER,
        replace(BASE, analog_output_mode="m67_synchronized", machine_m67_confirmed=False),
    )
    must(fallback.stats["analog_output_code_effective"] == "M68", "unconfirmed M67 did not fall back")
    must("M67 E0" not in fallback.gcode, "unconfirmed M67 leaked into G-code")
    checks.append("m67_requires_hal_confirmation")

    # 3. Confirmed M67 must queue E0/E2 directly before the first motion and pass audit.
    synced = generate_rotational_shell(
        CYLINDER,
        replace(BASE, analog_output_mode="m67_synchronized", machine_m67_confirmed=True),
    )
    must(synced.stats["analog_output_code_effective"] == "M67", "confirmed M67 not used")
    must(re.search(r"M67 E0 Q[0-9.]+.*\nM67 E2 Q[0-9.]+.*\nG91", synced.gcode) is not None, "M67 start sequence is not directly before motion block")
    synced_audit = audit_gcode(synced.gcode, replace(BASE, analog_output_mode="m67_synchronized", machine_m67_confirmed=True))
    must(synced_audit.stats["m67_without_following_motion"] == 0, "queued M67 left without motion")
    checks.append("confirmed_m67_synchronized")

    # 4. Zone updates: M67 updates are allowed inside the continuous block and are followed by motion.
    zoned_settings = replace(
        BASE,
        analog_output_mode="m67_synchronized",
        machine_m67_confirmed=True,
        experience_profile_enabled=True,
        experience_profile_json=profile_json(),
        experience_profile_apply_cfeed=True,
        experience_profile_apply_wire=True,
        experience_profile_apply_current=True,
        experience_profile_apply_z_step=True,
        experience_profile_update_m68_at_zone_boundaries=True,
    )
    zoned = generate_rotational_shell(CYLINDER, zoned_settings)
    must(zoned.stats["zone_output_updates_enabled"] is True, "zone updates not enabled")
    must(zoned.gcode.count("M67 E0") >= 2 and zoned.gcode.count("M67 E2") >= 2, "zonal M67 updates missing")
    zoned_audit = audit_gcode(zoned.gcode, zoned_settings)
    must(zoned_audit.stats["m67_without_following_motion"] == 0, "zonal M67 not followed by motion")
    checks.append("zonal_m67_updates")

    # 5. M68 zonal updates remain possible, but audit/report must flag blending risk.
    zoned_m68_settings = replace(zoned_settings, analog_output_mode="m68_compatible", machine_m67_confirmed=False)
    zoned_m68 = generate_rotational_shell(CYLINDER, zoned_m68_settings)
    must(zoned_m68.stats["analog_output_code_effective"] == "M68", "M68 zonal mode unavailable")
    must("breaks blending" in zoned_m68.audit_text, "M68 blending warning missing")
    checks.append("zonal_m68_warning")

    # 6. Fixed-X no-pause mode must reject changing-radius bowls/balloons instead of silently making wrong geometry.
    rejected = False
    try:
        generate_rotational_shell(TAPERED, BASE)
    except RuntimeError as exc:
        rejected = "near-constant-radius" in str(exc)
    must(rejected, "changing-radius no-pause geometry was not blocked")
    checks.append("radius_change_guard")

    # 7. G61 remains selectable, but report must warn about segment boundary slowdown.
    exact = generate_rotational_shell(CYLINDER, replace(BASE, path_control_mode="g61"))
    must("G61 (exact path" in exact.gcode, "G61 not emitted")
    must("conflicts with the no-pause objective" in exact.audit_text, "G61 no-pause warning missing")
    checks.append("planner_warning")

    # 8. Deposited-volume efficiency must be included consistently in E2 and J/mm3.
    eta06 = layer_parameters(0.0, 8.0, replace(BASE, deposition_efficiency=0.6))
    eta10 = layer_parameters(0.0, 8.0, replace(BASE, deposition_efficiency=1.0))
    must(eta06.wire_mm_s > eta10.wire_mm_s, "lower eta must require higher wire command")
    must(abs(eta06.energy_j_mm3 - eta10.energy_j_mm3) < 1e-6, "J/mm3 changed despite equal target deposited volume")
    checks.append("eta_mass_energy_consistency")

    # 9. Experience-profile recomputation must use the same eta convention as the base layer calculation.
    eta08_layer = layer_parameters(0.0, 8.0, BASE)
    eta08_recomputed = _recompute_layer_after_experience(
        eta08_layer, BASE, wire_mm_s=eta08_layer.wire_mm_s, current_ma=eta08_layer.current_ma
    )
    must(abs(eta08_recomputed.energy_j_mm3 - eta08_layer.energy_j_mm3) < 1e-9, "experience recompute lost eta")
    checks.append("experience_eta_consistency")

    # 10. Estimated bead width is geometric once auto-E2 has already compensated eta.
    bw06 = estimate_bead_width_mm(replace(BASE, deposition_efficiency=0.6), eta06)
    bw10 = estimate_bead_width_mm(replace(BASE, deposition_efficiency=1.0), eta10)
    must(abs(bw06 - bw10) < 1e-12, "bead-width estimate double-counted eta")
    checks.append("bead_width_no_double_eta")

    result = {
        "version": APP_VERSION,
        "cases_total": len(checks),
        "cases_ok": len(checks),
        "cases_failed": 0,
        "checks": checks,
    }
    Path("industrial_control_regression_results.json").write_text(
        json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
