from __future__ import annotations

import json
import math
from dataclasses import replace
from pathlib import Path

from ebam_gcode_studio.core import (
    APP_VERSION,
    ProcessSettings,
    _wire_for_target_wall,
    generate_rotational_shell,
)


CYLINDER = {
    "profile_type": "straight_cup",
    "height_mm": 2.0,
    "bottom_diameter_mm": 77.0,
    "top_diameter_mm": 77.0,
    "max_diameter_mm": 77.0,
    "wall_thickness_mm": 3.0,
    "bottom_solid_mm": 0.0,
    "resolution": 96,
}

BASE = ProcessSettings(
    layer_height=0.5,
    hatch_spacing=2.25,
    rotational_path_strategy="rotary_c_rings",
    rotational_radial_step_mm=2.25,
    rotary_c_motion_mode="no_pause_flat_rings",
    rotary_c_transition_angle_deg=17.0,
    rotary_c_max_deg_min=10000.0,
    feed_bottom_mm_min=299.433,
    feed_top_mm_min=299.433,
    voltage_kv=60.0,
    beam_current_mode="current",
    beam_current_bottom_ma=27.005,
    beam_current_top_ma=27.005,
    wire_diameter_mm=1.2,
    deposition_efficiency=1.0,
    wire_feed_mode="manual_constant",
    wire_feed_manual_mm_s=10.0,
    rotary_c_disable_layer_pauses=True,
    rotary_c_disable_w_retract=True,
    rotary_c_disable_z_hop=True,
    include_comments=True,
)


def must(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def main() -> None:
    checks: list[str] = []

    over = generate_rotational_shell(CYLINDER, BASE)
    must("MANUAL E2 x" in over.audit_text and "ПЕРЕПОДАЧА" in over.audit_text, "manual E2=10 overfeed warning missing")
    must(over.stats.get("wire_manual_deviation_flag") is True, "manual overfeed flag missing")
    checks.append("manual_10_overfeed_flagged")

    matched = generate_rotational_shell(CYLINDER, replace(BASE, wire_feed_manual_mm_s=5.0))
    must("ПЕРЕПОДАЧА" not in matched.audit_text and "НЕДОПОДАЧА" not in matched.audit_text, "near-lane E2 should stay inside advisory band")
    must(matched.stats.get("wire_manual_deviation_flag") is False, "near-lane E2 should not be flagged")
    checks.append("manual_5_lane_match")

    under = generate_rotational_shell(CYLINDER, replace(BASE, wire_feed_manual_mm_s=2.0))
    must("НЕДОПОДАЧА" in under.audit_text, "manual E2=2 underfeed warning missing")
    checks.append("manual_2_underfeed_flagged")

    dry = generate_rotational_shell(CYLINDER, replace(BASE, wire_feed_manual_mm_s=0.0))
    must("ПЕРЕПОДАЧА" not in dry.audit_text and "НЕДОПОДАЧА" not in dry.audit_text, "manual E2=0 dry run must remain intentional")
    checks.append("manual_0_dry_run_allowed")

    auto = generate_rotational_shell(CYLINDER, replace(BASE, wire_feed_mode="auto"))
    must("wire_manual_deviation_flag" not in auto.stats, "auto wire mode must not use manual deviation flag")
    checks.append("auto_skips_manual_sanity")

    must("ПОДВОД НА МАЛОЙ ВЫСОТЕ" in over.audit_text, "low-Z approach warning missing")
    checks.append("low_z_approach_flagged")

    e2_target = _wire_for_target_wall(3.0, 0.5, 299.433, 1.2, 1.0)
    must(math.isclose(e2_target, 6.6189, rel_tol=5e-4), f"unexpected 3-mm target E2: {e2_target}")
    checks.append("target_3mm_model_is_6_62_mm_s")

    must(f"Generated by EBAM G-code Studio {APP_VERSION}" in over.gcode, "current version missing from G-code")
    checks.append("version_header_matches_core")

    result = {
        "version": APP_VERSION,
        "cases_total": len(checks),
        "cases_ok": len(checks),
        "cases_failed": 0,
        "checks": checks,
        "target_3mm_model_e2_mm_s": round(e2_target, 6),
        "qualification": "model_only_requires_machine_TEST",
    }
    Path("wire_sanity_regression_results.json").write_text(
        json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
